import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.mime.application import MIMEApplication
import os
from dotenv import load_dotenv
import pdfkit
import platform
import subprocess
import json

load_dotenv()

class EmailService:
    def __init__(self):
        self.smtp_server = os.getenv('SMTP_SERVER', 'smtp.gmail.com')
        self.smtp_port = int(os.getenv('SMTP_PORT', 587))
        self.smtp_username = os.getenv('SMTP_USERNAME')
        self.smtp_password = os.getenv('SMTP_PASSWORD')
        self.sender_email = os.getenv('SENDER_EMAIL')
        
        self.wkhtmltopdf_path = os.getenv('WKHTMLTOPDF_PATH')
        
        if not self.wkhtmltopdf_path or not os.path.exists(self.wkhtmltopdf_path):
            print("Warning: wkhtmltopdf not found. PDF generation will be disabled.")
            print("Please install wkhtmltopdf from: https://wkhtmltopdf.org/downloads.html")
            print("After installation, set WKHTMLTOPDF_PATH in your .env file")
            self.pdfkit_config = None
        else:
            print(f"Using wkhtmltopdf from: {self.wkhtmltopdf_path}")
            self.pdfkit_config = pdfkit.configuration(wkhtmltopdf=self.wkhtmltopdf_path)

        self.pdf_options = {
            'page-size': 'A4',
            'margin-top': '0.75in',
            'margin-right': '0.75in',
            'margin-bottom': '0.75in',
            'margin-left': '0.75in',
            'encoding': "UTF-8",
            'no-outline': None
        }

    def create_packing_pdf(self, packing_data):
        """Create PDF from packing list"""
        if not self.pdfkit_config:
            raise Exception("PDF generation is not available - wkhtmltopdf not installed")

        html_content = f"""
        <html>
            <head>
                <meta charset="UTF-8">
                <style>
                    body {{ 
                        font-family: Arial, sans-serif;
                        line-height: 1.6;
                        color: #333;
                    }}
                    .header {{ 
                        text-align: center;
                        color: #2c3e50;
                        padding: 20px 0;
                        border-bottom: 2px solid #eee;
                    }}
                    .packing-section {{
                        margin: 20px 0;
                        padding: 15px;
                    }}
                    .category {{
                        background: #f5f6fa;
                        padding: 10px;
                        margin: 10px 0;
                        border-radius: 5px;
                    }}
                    .eco-tips {{
                        background: #e8f5e9;
                        padding: 15px;
                        margin: 20px 0;
                        border-radius: 5px;
                    }}
                    .footer {{
                        text-align: center;
                        margin-top: 30px;
                        padding-top: 20px;
                        border-top: 1px solid #eee;
                        font-size: 0.9em;
                        color: #666;
                    }}
                </style>
            </head>
            <body>
                <div class="header">
                    <h1>Smart Packing List</h1>
                </div>
                <div class="packing-section">
                    <h2>Trip Details</h2>
                    <p><strong>Duration:</strong> {packing_data.get('duration')} days</p>
                    <p><strong>Destination:</strong> {packing_data.get('destination')}</p>
                    <p><strong>Travelers:</strong> {packing_data.get('travelers')}</p>
                    <p><strong>Season:</strong> {packing_data.get('season')}</p>
                </div>
                <div class="packing-section">
                    {packing_data.get('packing_list', '')}
                </div>
                <div class="eco-tips">
                    <h2>Eco-friendly Tips</h2>
                    <p>{packing_data.get('eco_tips', '')}</p>
                    <p><strong>Estimated Weight:</strong> {packing_data.get('weight_estimate', '')}</p>
                    <p><strong>Carbon Impact:</strong> {packing_data.get('carbon_impact', '')}</p>
                </div>
                <div class="footer">
                    <p>Generated by Hidden Haddi Smart Packer</p>
                </div>
            </body>
        </html>
        """
        
        try:
            pdf_path = f"temp/packing_list_{packing_data.get('id', 'temp')}.pdf"
            os.makedirs('temp', exist_ok=True)
            
            pdfkit.from_string(
                html_content,
                pdf_path,
                configuration=self.pdfkit_config,
                options=self.pdf_options
            )
            return pdf_path
            
        except Exception as e:
            print(f"PDF creation error: {str(e)}")
            raise Exception(f"Failed to create PDF: {str(e)}")

    def send_packing_list(self, email, packing_data):
        """Send packing list via email"""
        try:
            pdf_path = self.create_packing_pdf(packing_data)

            msg = MIMEMultipart()
            msg['From'] = self.sender_email
            msg['To'] = email
            msg['Subject'] = "Your Smart Packing List from Hidden ಹಾದಿ"

            body = """
            Dear Traveler,

            Thank you for using Hidden ಹಾದಿ Smart Packer! Please find your personalized packing list attached.

            Safe Travels!
            Team Hidden ಹಾದಿ
            """
            msg.attach(MIMEText(body, 'plain'))

            with open(pdf_path, 'rb') as f:
                pdf = MIMEApplication(f.read(), _subtype='pdf')
                pdf.add_header('Content-Disposition', 'attachment', 
                             filename='packing_list.pdf')
                msg.attach(pdf)

            with smtplib.SMTP(self.smtp_server, self.smtp_port) as server:
                server.starttls()
                server.login(self.smtp_username, self.smtp_password)
                server.send_message(msg)

            if os.path.exists(pdf_path):
                os.remove(pdf_path)
            
            return {'success': True}

        except Exception as e:
            print(f"Error sending packing list email: {str(e)}")
            return {'success': False, 'error': str(e)}

    def create_travel_pdf(self, trip_data):
        """Create PDF from travel plan with route information"""
        if not self.pdfkit_config:
            raise Exception("PDF generation is not available - wkhtmltopdf not installed")

        # Generate Google Maps route link
        destinations = trip_data.get('destinations', [])
        if destinations:
            maps_link = "https://www.google.com/maps/dir/?api=1&"
            maps_link += f"origin={destinations[0]}&destination={destinations[-1]}"
            if len(destinations) > 2:
                waypoints = "|".join(destinations[1:-1])
                maps_link += f"&waypoints={waypoints}"
        else:
            maps_link = ""

        html_content = f"""
        <html>
            <head>
                <meta charset="UTF-8">
                <style>
                    body {{ 
                        font-family: Arial, sans-serif;
                        line-height: 1.6;
                        color: #333;
                    }}
                    .header {{ 
                        text-align: center;
                        color: #2c3e50;
                        padding: 20px 0;
                        border-bottom: 2px solid #eee;
                    }}
                    .trip-details {{ 
                        margin: 20px 0;
                        padding: 15px;
                        background: #f5f6fa;
                        border-radius: 5px;
                    }}
                    .itinerary {{ 
                        margin: 20px 0;
                        padding: 10px;
                    }}
                    .route-info {{
                        margin: 20px 0;
                        padding: 15px;
                        background: #e8f5e9;
                        border-radius: 5px;
                    }}
                    .footer {{
                        text-align: center;
                        margin-top: 30px;
                        padding-top: 20px;
                        border-top: 1px solid #eee;
                        font-size: 0.9em;
                        color: #666;
                    }}
                </style>
            </head>
            <body>
                <div class="header">
                    <h1>Travel Plan</h1>
                </div>
                <div class="trip-details">
                    <p><strong>Dates:</strong> {trip_data['start_date']} to {trip_data['end_date']}</p>
                    <p><strong>Travelers:</strong> {trip_data['travelers']}</p>
                    <p><strong>Budget:</strong> {trip_data['budget']}</p>
                </div>
                <div class="route-info">
                    <h2>Route Information</h2>
                    <p><strong>View Route on Google Maps:</strong></p>
                    <p><a href="{maps_link}">{maps_link}</a></p>
                </div>
                <div class="itinerary">
                    {trip_data['itinerary']}
                </div>
                <div class="footer">
                    <p>Generated by Hidden Haddi Travel Planner</p>
                </div>
            </body>
        </html>
        """
        
        try:
            pdf_path = f"temp/travel_plan_{trip_data.get('id', 'temp')}.pdf"
            os.makedirs('temp', exist_ok=True)
            
            pdfkit.from_string(
                html_content,
                pdf_path,
                configuration=self.pdfkit_config,
                options=self.pdf_options
            )
            return pdf_path, maps_link
            
        except Exception as e:
            print(f"PDF creation error: {str(e)}")
            raise Exception(f"Failed to create PDF: {str(e)}")

    def send_travel_plan(self, email, trip_data):
        """Send travel plan via email with route information"""
        try:
            pdf_path, maps_link = self.create_travel_pdf(trip_data)

            msg = MIMEMultipart()
            msg['From'] = self.sender_email
            msg['To'] = email
            msg['Subject'] = "Your Travel Plan from Hidden ಹಾದಿ"

            body = f"""
            Dear Traveler,

            Thank you for using Hidden ಹಾದಿ! Please find your travel plan attached.

            View your route on Google Maps:
            {maps_link}

            Happy Travels!
            Team Hidden ಹಾದಿ
            """
            msg.attach(MIMEText(body, 'plain'))

            with open(pdf_path, 'rb') as f:
                pdf = MIMEApplication(f.read(), _subtype='pdf')
                pdf.add_header('Content-Disposition', 'attachment', 
                             filename='travel_plan.pdf')
                msg.attach(pdf)

            with smtplib.SMTP(self.smtp_server, self.smtp_port) as server:
                server.starttls()
                server.login(self.smtp_username, self.smtp_password)
                server.send_message(msg)

            if os.path.exists(pdf_path):
                os.remove(pdf_path)
            
            return {'success': True}

        except Exception as e:
            print(f"Error sending travel plan email: {str(e)}")
            return {'success': False, 'error': str(e)}

    def create_route_pdf(self, route_data):
        """Create PDF with route details and Google Maps link"""
        html_content = f"""
        <!DOCTYPE html>
        <html>
            <head>
                <style>
                    body {{ font-family: Arial, sans-serif; line-height: 1.6; }}
                    .header {{ text-align: center; padding: 20px; }}
                    .route-details {{ margin: 20px; }}
                    .maps-link {{ margin: 20px; word-break: break-all; }}
                    .summary {{ margin: 20px; background: #f5f5f5; padding: 15px; }}
                </style>
            </head>
            <body>
                <div class="header">
                    <h1>Your Route Details</h1>
                </div>
                <div class="route-details">
                    <h2>Journey Information</h2>
                    <p><strong>From:</strong> {route_data['origin']}</p>
                    <p><strong>To:</strong> {route_data['destination']}</p>
                    <p><strong>Mode of Transport:</strong> {route_data['mode']}</p>
                </div>
                <div class="summary">
                    <h2>Route Summary</h2>
                    {route_data['summary']}
                </div>
                <div class="maps-link">
                    <h2>Google Maps Link</h2>
                    <p>Click here to view your route on Google Maps:</p>
                    <a href="{route_data['maps_link']}">{route_data['maps_link']}</a>
                </div>
            </body>
        </html>
        """
        
        try:
            pdf_path = f"temp/route_details_{route_data['id']}.pdf"
            os.makedirs('temp', exist_ok=True)
            
            pdfkit.from_string(
                html_content,
                pdf_path,
                configuration=self.pdfkit_config,
                options=self.pdf_options
            )
            return pdf_path
        
        except Exception as e:
            print(f"PDF creation error: {str(e)}")
            raise Exception(f"Failed to create PDF: {str(e)}")

    def send_route_details(self, email, route_data):
        """Send route details via email with PDF attachment"""
        try:
            pdf_path = self.create_route_pdf(route_data)

            msg = MIMEMultipart()
            msg['From'] = self.sender_email
            msg['To'] = email
            msg['Subject'] = "Your Route Details from Hidden ಹಾದಿ"

            body = f"""
            Dear Traveler,

            Thank you for using Hidden ಹಾದಿ Route Planner! 
        
            Your route from {route_data['origin']} to {route_data['destination']} is ready.
        
            View your route on Google Maps:
            {route_data['maps_link']}

            Please find your detailed route information in the attached PDF.

            Safe Travels!
            Team Hidden ಹಾದಿ
            """
            msg.attach(MIMEText(body, 'plain'))

            with open(pdf_path, 'rb') as f:
                pdf = MIMEApplication(f.read(), _subtype='pdf')
                pdf.add_header('Content-Disposition', 'attachment', 
                             filename='route_details.pdf')
                msg.attach(pdf)

            with smtplib.SMTP(self.smtp_server, self.smtp_port) as server:
                server.starttls()
                server.login(self.smtp_username, self.smtp_password)
                server.send_message(msg)

            if os.path.exists(pdf_path):
                os.remove(pdf_path)
        
            return {'success': True}

        except Exception as e:
            print(f"Error sending route details email: {str(e)}")
            return {'success': False, 'error': str(e)}

    def _format_route_details(self, details):
        """Helper method to format route details into HTML"""
        if not details:
            return "<p>No route details available</p>"
        
        try:
            details_dict = details if isinstance(details, dict) else json.loads(details)
            
            html = "<div class='route-steps'>"
            
            if 'distance' in details_dict:
                html += f"<p><strong>Total Distance:</strong> {details_dict['distance']}</p>"
            if 'duration' in details_dict:
                html += f"<p><strong>Estimated Duration:</strong> {details_dict['duration']}</p>"
            
            if 'steps' in details_dict:
                html += "<h4>Route Steps:</h4><ol>"
                for step in details_dict['steps']:
                    html += f"<li>{step}</li>"
                html += "</ol>"
                
            html += "</div>"
            return html
            
        except Exception as e:
            print(f"Error formatting route details: {str(e)}")
            return "<p>Error formatting route details</p>"

    def _send_email(self, msg):
        """Helper method to send email with better error handling"""
        try:
            if not all([self.smtp_server, self.smtp_port, self.smtp_username, 
                       self.smtp_password, self.sender_email]):
                raise ValueError("Missing email configuration. Check SMTP settings in .env file")

            with smtplib.SMTP(self.smtp_server, self.smtp_port) as server:
                server.starttls()
                server.login(self.smtp_username, self.smtp_password)
                server.send_message(msg)
                
        except smtplib.SMTPAuthenticationError:
            print("SMTP Authentication failed. Check username and password.")
            raise
        except smtplib.SMTPException as e:
            print(f"SMTP error occurred: {str(e)}")
            raise
        except Exception as e:
            print(f"Unexpected error in _send_email: {str(e)}")
            raise

    def send_footprint_details(self, email, footprint_data):
        """Send carbon footprint calculation details via email"""
        try:
            required_fields = ['id', 'origin', 'destination', 'transport', 
                             'distance', 'total_emissions', 'maps_link']
            missing_fields = [field for field in required_fields 
                             if field not in footprint_data]
            
            if missing_fields:
                raise ValueError(f"Missing required data: {', '.join(missing_fields)}")

            if not email or '@' not in email:
                raise ValueError("Invalid email address")

            os.makedirs('temp', exist_ok=True)
            pdf_path = f"temp/carbon_footprint_{footprint_data['id']}.pdf"

            try:
                # Generate HTML content (your existing HTML template code here)
                html_content = f"""
                <!-- Your existing HTML template -->
                """
                
                # Verify PDF configuration
                if not self.pdfkit_config:
                    raise Exception("PDF configuration not available - check wkhtmltopdf installation")

                # Generate PDF
                pdfkit.from_string(
                    html_content,
                    pdf_path,
                    configuration=self.pdfkit_config,
                    options=self.pdf_options
                )

                # Verify PDF was created
                if not os.path.exists(pdf_path):
                    raise Exception("PDF file was not created")

                msg = MIMEMultipart()
                msg['From'] = self.sender_email
                msg['To'] = email
                msg['Subject'] = "Your Carbon Footprint Report from Hidden ಹಾದಿ"

                body = f"""
                Dear Traveler,

                Thank you for using Hidden ಹಾದಿ Carbon Footprint Calculator!

                Your journey from {footprint_data['origin']} to {footprint_data['destination']} 
                has a total carbon footprint of {footprint_data['total_emissions']:.2f} kg CO2.

                View your route on Google Maps:
                {footprint_data['maps_link']}

                Please find your detailed carbon footprint report attached.

                Together for a greener future,
                Team Hidden ಹಾದಿ
                """
                msg.attach(MIMEText(body, 'plain'))

                # Attach PDF
                try:
                    with open(pdf_path, 'rb') as f:
                        pdf = MIMEApplication(f.read(), _subtype='pdf')
                        pdf.add_header('Content-Disposition', 'attachment', 
                                     filename='carbon_footprint_report.pdf')
                        msg.attach(pdf)
                except Exception as e:
                    raise Exception(f"Error attaching PDF: {str(e)}")

                # Send email
                self._send_email(msg)

            finally:
                # Clean up PDF file
                if os.path.exists(pdf_path):
                    try:
                        os.remove(pdf_path)
                    except Exception as e:
                        print(f"Warning: Could not delete temporary PDF file: {str(e)}")

            return {'success': True}

        except ValueError as e:
            print(f"Validation error in send_footprint_details: {str(e)}")
            return {'success': False, 'error': str(e)}
        except Exception as e:
            print(f"Error in send_footprint_details: {str(e)}")
            return {'success': False, 'error': "Failed to send email. Please check your email configuration."}




